### //              Variables              // ###
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNzQxMDVlNGQ3NzNjZTU4ZDJlNmMiLCJyb2xlIjpbImFkbWluIl0sImlhdCI6MTcxNDQxMzg0MCwiZXhwIjoxNzE0NDQyNjQwfQ.wUY9qXfkJzlkfd2FVepEdCDREw9fjUL0dtdp75rZk5s
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJhMzYxNWQxOGM5OWViOTlkOTE5NTAiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzE0MTI0MTY4LCJleHAiOjE3MTQxNTI5Njh9.3VWTp3WV3Sz27DntuY3Mk_G2B3AgC3BVXKT9uEJs9Mo

@tokenComercio = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNzRmMDVlNGQ3NzNjZTU4ZDJlNzAiLCJpYXQiOjE3MTQ0MTU4MzMsImV4cCI6MTcxNDQ0NDYzM30._TvcRQqGFdcijZ5o6BYuySPwEwYyUbk6awpvwMvqmhI

@idUSerTest = 662a3615d18c99eb99d91950
@idAdmin = 662b74105e4d773ce58d2e6c
### ---------------- CRUD Strorage ----------------

### ------POST------
### 
POST http://localhost:3000/api/storage/postImg HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="we_are_so_back.jpeg"
Content-Type: image/jpeg

< ./we_are_so_back.jpeg
--Boundry--
###
POST http://localhost:3000/api/storage/postVideo HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="video"; filename="gatinho.mp4"
Content-Type: video/mp4

< ./gatinho.mp4
--Boundry--
###
POST http://localhost:3000/api/storage/postFile HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="file"; filename="ejercicios_tema_2.pdf"
Content-Type: application/pdf

< ./path_to_your_file/ejercicios_tema_2.pdf
--Boundry--

### ------GET------
###
GET http://localhost:3000/api/storage/ HTTP/1.1
###
GET http://localhost:3000/api/storage/66283b3d4adf9c130ef8d4e5 HTTP/1.1

### ------DELETE------
###
DELETE http://localhost:3000/api/storage/softDelete/66284229d01227f22d8b1543 HTTP/1.1
###
DELETE http://localhost:3000/api/storage/totalDelete/66284226d01227f22d8b1541 HTTP/1.1



### ---------------- CRUD User ----------------

### ------POST------
###
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "nombre": "davidAdmin",
    "email": "david@mail.com",
    "password": "admin",
    "edad": 25,
    "ciudad": "Madrid",
    "roles": ["user"],
    "recibirOfertas" : true
}
###
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "manolin@mail.com",
    "password": "123456"
}

### ------GET------
###
GET http://localhost:3000/api/auth/ HTTP/1.1
Authorization: Bearer {{tokenUser}}

### ------PATCH------
###
PATCH http://localhost:3000/api/auth/{{idAdmin}} HTTP/1.1
Content-Type: application/json

{
    "nombre": "David Admin",
    "role": ["admin"]
}

### ------DELETE------
###
DELETE http://localhost:3000/api/auth/softDelete/662a34ff620dd9802e817117 HTTP/1.1
###
DELETE http://localhost:3000/api/auth/totalDelete/662a2e522a21b07407db70ec HTTP/1.1


### ---------------- CRUD Comercios  ----------------

### ------POST------
###
POST http://localhost:3000/api/comercios/ HTTP/1.1
Content-Type: application/json

{
    "nombreComercio": "El Corte Ingles",
    "cif": "A12345678",
    "direccion": "Calle Gran Via 1",
    "email": "corteIngles@mail.com",
    "telefono": 912345678
}

### ------GET------
###
GET http://localhost:3000/api/comercios/ HTTP/1.1
###
GET http://localhost:3000/api/comercios/662aa777ed2527c0d755f2b1 HTTP/1.1

### ------PATCH------
###
PATCH http://localhost:3000/api/comercios/662aa777ed2527c0d755f2b1 HTTP/1.1
Content-Type: application/json

{
    "telefono": 111111111
}

### ------DELETE------
###
DELETE http://localhost:3000/api/comercios/softDelete/662aa777ed2527c0d755f2b1 HTTP/1.1
###
DELETE http://localhost:3000/api/comercios/totalDelete/662aa777ed2527c0d755f2b1 HTTP/1.1


### ---------------- CRUD Webs  ----------------

### ------POST------
###
POST http://localhost:3000/api/webs/ HTTP/1.1
Content-Type: application/json

{
    "ciudad": "Benavente",
    "actividad": "Cine",
    "titulo": "Cine Benavente",
    "resumen": "UN cine de toda la vida",
    "textos":[
        "Cine de toda la vida",
        "Viva el cine",
        "Cine para todos"
    ],
    "fotos" : [
        "66284224d01227f22d8b153f"
    ],
    "idComercio": "662ac1f5acb591a5bc2d294f"
}

### ------GET------
###
GET http://localhost:3000/api/webs/ HTTP/1.1
###
GET http://localhost:3000/api/webs/662ac86381da418c0773b6e0 HTTP/1.1

### ------PATCH------
###
PATCH http://localhost:3000/api/webs/662ac86381da418c0773b6e0 HTTP/1.1
Content-Type: application/json

{
    "reseñas": [
        {"texto": "Me encanta", "puntuacion": 5, "idUsuario": "662a3615d18c99eb99d91950" },
        {"texto": "No me gusta", "puntuacion": 1, "idUsuario":"662a3615d18c99eb99d99999"}
    ]
}

### ------DELETE------
###
DELETE http://localhost:3000/api/webs/totalDelete/662ac84b81da418c0773b6dd HTTP/1.1
###
DELETE http://localhost:3000/api/webs/softDelete/662ac84b81da418c0773b6dd HTTP/1.1


###  ---------------- Requisitos funcionales  ----------------
  
# 1.- Solo un admin puede registrar un comercio, después facilitará el token JWT a este.

# router.post("/", authMiddleware, checkRol(['admin']), validatorCreateItem, createItem)

### Login como admin
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "david@mail.com",
    "password": "admin"
}
### Login como user
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "manolin@mail.com",
    "password": "123456"
}
###
POST http://localhost:3000/api/comercios/ HTTP/1.1
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
    "nombreComercio": "El Corte CR8",
    "cif": "CR8",
    "direccion": "Calle CR8 1",
    "email": "CR8@mail.com",
    "telefono": 888
}

###
# 2.- El comercio solo podrá subir/actualizar contenido en su propia página y requiere de un
# token JWT para hacerlo. Pero no puede modificar el Scoring, la cantidad de votaciones ni
# las reseñas. El comercio puede darse de baja y borrar su página

# router.patch("/:id", authMiddleware, checkRol(['comercio']), validatorUpdateItem, updateItem)
# router.delete("/softDelete/:id", authMiddleware, checkRol(['comercio']), softDeleteItem)
GET http://localhost:3000/api/comercios/ HTTP/1.1
###
GET http://localhost:3000/api/comercios/662b74f05e4d773ce58d2e70 HTTP/1.1
###
PATCH http://localhost:3000/api/comercios/ HTTP/1.1
Authorization: Bearer {{tokenComercio}}
Content-Type: application/json

{
    "scoring": 123
}
###
DELETE http://localhost:3000/api/comercios/true HTTP/1.1
Authorization: Bearer {{tokenComercio}}
